apiVersion: v1
kind: Service
metadata:
  name: httpd-svc-24
spec:
  selector:
    run: httpd-dep-24
  ports:
  - port: 80
    name: http-tcp
    targetPort: 80
    protocol: TCP
  externalIPs: ["192.168.254.24"]
