apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-24
spec:
  selector:
    run: nginx-dep-24
  ports:
  - port: 80
    name: http-tcp
    targetPort: 80
    protocol: TCP
  externalIPs: ["192.168.0.24"]
