apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc-21
spec:
  selector:
    run: mariadb-dep
  ports:
  - port: 3306
    name: tcp-3306
    targetPort: 3306
    protocol: TCP
  externalIPs: ["192.168.0.33"]
