apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-23
spec:
  selector:
    run: nginx-dep-23
  ports:
  - port: 80
    name: http-tcp
    targetPort: 80
    protocol: TCP
  externalIPs: ["192.168.0.23"]
