apiVersion: v1
kind: Service
metadata:
  name: pdns-svc-23-24
  namespace: default
  labels:
    app: pdns-dep
spec:
  ports:
  - name: pdns-udp-53
    port: 53
    protocol: UDP
    targetPort: 53
  - name: pdns-tcp-53
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    run: pdns-dep
  externalIPs: ["192.168.254.23","192.168.254.24"]
