apiVersion: v1
kind: Service
metadata:
  name: bind-svc-22
spec:
  selector:
    run: bind-22
  ports:
  - port: 53
    name: dns-tcp
    targetPort: 53
    protocol: TCP
  - port: 53
    name: dns-udp
    targetPort: 53
    protocol: UDP
  externalIPs: ["192.168.254.22"]
