apiVersion: v1
kind: Service
metadata:
  name: wildfly-svc-22
spec:
  selector:
    run: wildfly-dep-22
  ports:
  - port: 8080
    name: tcp-8080
    targetPort: 8080
    protocol: TCP
  externalIPs: ["192.168.0.22"]
